/**
 * Convenience aliases over the auto-generated OpenAPI schema. The schema
 * itself lives in api.ts and is regenerated by `npm run gen:types`.
 *
 * Add new aliases here when a component would otherwise have to type
 * `components["schemas"]["..."]` repeatedly.
 */
import type { components } from './api';

type Schemas = components['schemas'];

export type UserProfile = Schemas['UserProfileResponse'];
export type UserResumeResponse = Schemas['UserResumeResponse'];

export type Job = Schemas['JobResponse'];
export type JobListResponse = Schemas['JobListResponse'];
export type JobCreate = Schemas['JobCreate'];

export type Session = Schemas['SessionResponse'];
export type SessionListResponse = Schemas['SessionListResponse'];
export type SessionStatus = Schemas['SessionStatusResponse'];
export type SessionStatusValue = Schemas['SessionStatus'];
export type QuestionItem = Schemas['QuestionItem'];
export type TokenUsage = Schemas['TokenUsage'];

export type CoachRequest = Schemas['CoachRequest'];
export type CoachResponse = Schemas['CoachResponse'];
